### ISSUE TITLE
add 1.17.1

### ISSUE THREAD

**Issue by fr3d3lin** [acranum/ChestShop#3]
hello, can you add paper 1.17.1 please :D 

`[06:23:16] [Server thread/ERROR]: Could not load 'plugins/ChestShop.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
at org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:358) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by acranum** [comment]
Hey @fr3d3lin,
Since the plugin is supposed to be very simple and easy, I don't want to include a version control. Nevertheless, I would like to give you access to the plugin, which is why I can give you this beta version for 1.17, but it may not work as smoothly as the current version from 1.19, but should still support all current features. Since I have not tested the version sufficiently, minor problems may occur. So if there are further bugs, please report them.
[ChestShop_1.17.1.zip](https://github.com/user-attachments/files/17781198/ChestShop_1.17.1.zip)

**Comment by fr3d3lin** [comment]
a big thank you, I'll let you know if there's anything.
